export const SHORTCUTS = {
  editorShortcuts: [
    { action: "Bold", shortcut: ["mod", "B"] },
    { action: "Italic", shortcut: ["mod", "I"] },
    { action: "Underline", shortcut: ["mod", "U"] },
    { action: "Undo", shortcut: ["mod", "Z"] },
    { action: "Redo", shortcut: ["mod", "shift", "Z"] },
    { action: "Inline Code", shortcut: ["mod", "E"] },
    { action: "Select All", shortcut: ["mod", "A"] },
    { action: "Copy", shortcut: ["mod", "C"] },
    { action: "Paste", shortcut: ["mod", "V"] },
  ],
  markdownSyntax: [
    { action: "Heading 1", syntax: "# Heading 1" },
    { action: "Heading 2", syntax: "## Heading 2" },
    { action: "Bold", syntax: "**bold**" },
    { action: "Italic", syntax: "*italic*" },
    { action: "Strikethrough", syntax: "~~strike~~" },
    { action: "Inline Code", syntax: "`code`" },
    { action: "Code Block", syntax: "```js ... ```" },
    { action: "Bullet List", syntax: "- item" },
    { action: "Ordered List", syntax: "1. item" },
    { action: "Blockquote", syntax: "> quote" },
    { action: "Horizontal Rule", syntax: "---" },
    { action: "Link", syntax: "[text](url)" },
    { action: "Image", syntax: "![alt](url)" },
  ],
  appShortcuts: [
    { action: "New Journal Entry", shortcut: ["mod", "N"] },
    { action: "Generate Heading", shortcut: ["mod", "G"] },
    { action: "Search Journals", shortcut: ["mod", "K"] },
    { action: "Toggle Theme", shortcut: ["mod", "T"] },
  ],
};
