root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "frontend"]
include_dir = []
exclude_file = []
log = "air.log"
# Reduced delay from 1000ms to 100ms for faster reloading
delay = 100
stop_on_error = true
send_interrupt = false
kill_delay = 500

[log]
time = true

# Add these sections for better performance
[screen]
clear_on_rebuild = true

[misc]
clean_on_exit = true