# .air.toml

[build]
  cmd = "go build -o tmp/main ./cmd/server"
  bin = "tmp/main"
  full_bin = ""
  delay = 1000 # ms
  exclude_dir = ["tmp", "vendor", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_ext = ["swp", "tmp"]
  log = "air_errors.log"

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"