version: "3.8"

services:
  slate-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slate-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/data/slate.db
    volumes:
      # Remove the app volume mount as it conflicts with the container
      - slate-data:/data
    networks:
      slate-network:
        aliases:
          - api.slate.com
    restart: unless-stopped

networks:
  slate-network:
    driver: bridge

volumes:
  slate-data:
    driver: local
